version: '3'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - hbx-network
    volumes:
      - ./uploads:/usr/src/app/plan-validator/web
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.production
    ports:
      - "80:80"
    networks:
      - hbx-network
    volumes:
      - $PWD/nginx/configs/production/upstream.conf:/etc/nginx/conf.d/upstream.conf
networks:
  hbx-network:
    driver: bridge