version: '3'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.production
    ports:
      - "80:80"
    volumes:
      - $PWD/nginx/configs/production/upstream.conf:/etc/nginx/conf.d/upstream.conf